#:kivy 2.2.0

MDScreen: 
    name:'home'
    MDCard:
        orientation: 'vertical'
        size_hint: None, None
        style: "elevated"
        size: '400dp','600dp'
        pos_hint: {'center_x': .5, 'center_y': .5}
        padding: 10
        spacing: 10
        MDLabel:
            text: 'home'
            halign: 'center'
            font_style: 'H4'
        MDRaisedButton:
            text: 'to change theme'
            on_release:app.theme() 